name: Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
    strategy:
      fail-fast: false
      matrix:
        elixir: ["1.19.0"]
        otp: ["28.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Run benchmark
        run: mix run --no-start bench/benchmark.exs
